import { NextResponse } from "next/server";
import { executeVos, queryVos } from "@/lib/vos-db";
import { verifySession } from "@/lib/auth";

const SEED_DATA = [
  // ====== North America ======
  { country: "United States", operator: "AT&T", mcc: "310", mnc: "410" },
  { country: "United States", operator: "T-Mobile", mcc: "310", mnc: "260" },
  { country: "United States", operator: "Verizon", mcc: "310", mnc: "012" },
  { country: "United States", operator: "Sprint/T-Mobile", mcc: "310", mnc: "120" },
  { country: "United States", operator: "US Cellular", mcc: "311", mnc: "220" },
  { country: "United States", operator: "Dish Wireless", mcc: "313", mnc: "100" },
  { country: "Canada", operator: "Bell Mobility", mcc: "302", mnc: "610" },
  { country: "Canada", operator: "Rogers Wireless", mcc: "302", mnc: "720" },
  { country: "Canada", operator: "Telus Mobility", mcc: "302", mnc: "220" },
  { country: "Canada", operator: "Freedom Mobile", mcc: "302", mnc: "490" },
  { country: "Canada", operator: "Videotron", mcc: "302", mnc: "500" },
  { country: "Mexico", operator: "Telcel", mcc: "334", mnc: "020" },
  { country: "Mexico", operator: "Movistar", mcc: "334", mnc: "030" },
  { country: "Mexico", operator: "AT&T Mexico", mcc: "334", mnc: "090" },

  // ====== Latin America ======
  { country: "Brazil", operator: "Vivo", mcc: "724", mnc: "06" },
  { country: "Brazil", operator: "Claro", mcc: "724", mnc: "05" },
  { country: "Brazil", operator: "TIM Brasil", mcc: "724", mnc: "02" },
  { country: "Brazil", operator: "Oi", mcc: "724", mnc: "31" },
  { country: "Argentina", operator: "Movistar", mcc: "722", mnc: "07" },
  { country: "Argentina", operator: "Personal", mcc: "722", mnc: "34" },
  { country: "Argentina", operator: "Claro AR", mcc: "722", mnc: "310" },
  { country: "Colombia", operator: "Claro", mcc: "732", mnc: "101" },
  { country: "Colombia", operator: "Movistar", mcc: "732", mnc: "123" },
  { country: "Colombia", operator: "Tigo", mcc: "732", mnc: "103" },
  { country: "Chile", operator: "Entel", mcc: "730", mnc: "01" },
  { country: "Chile", operator: "Movistar", mcc: "730", mnc: "02" },
  { country: "Chile", operator: "Claro", mcc: "730", mnc: "03" },
  { country: "Chile", operator: "WOM", mcc: "730", mnc: "09" },
  { country: "Peru", operator: "Movistar", mcc: "716", mnc: "06" },
  { country: "Peru", operator: "Claro", mcc: "716", mnc: "10" },
  { country: "Peru", operator: "Entel Peru", mcc: "716", mnc: "17" },
  { country: "Ecuador", operator: "Claro", mcc: "740", mnc: "01" },
  { country: "Ecuador", operator: "Movistar", mcc: "740", mnc: "00" },
  { country: "Venezuela", operator: "Movistar", mcc: "734", mnc: "04" },
  { country: "Venezuela", operator: "Digitel", mcc: "734", mnc: "02" },
  { country: "Dominican Republic", operator: "Claro", mcc: "370", mnc: "02" },
  { country: "Dominican Republic", operator: "Altice", mcc: "370", mnc: "01" },
  { country: "Guatemala", operator: "Claro", mcc: "704", mnc: "01" },
  { country: "Guatemala", operator: "Tigo", mcc: "704", mnc: "02" },
  { country: "Panama", operator: "Cable & Wireless", mcc: "714", mnc: "01" },
  { country: "Panama", operator: "Tigo", mcc: "714", mnc: "03" },
  { country: "Costa Rica", operator: "Kolbi (ICE)", mcc: "712", mnc: "01" },
  { country: "Costa Rica", operator: "Claro", mcc: "712", mnc: "03" },
  { country: "Honduras", operator: "Tigo", mcc: "708", mnc: "001" },
  { country: "Honduras", operator: "Claro", mcc: "708", mnc: "002" },
  { country: "El Salvador", operator: "Claro", mcc: "706", mnc: "01" },
  { country: "El Salvador", operator: "Tigo", mcc: "706", mnc: "03" },
  { country: "Nicaragua", operator: "Claro", mcc: "710", mnc: "21" },
  { country: "Nicaragua", operator: "Tigo", mcc: "710", mnc: "73" },
  { country: "Bolivia", operator: "Entel", mcc: "736", mnc: "02" },
  { country: "Bolivia", operator: "Tigo", mcc: "736", mnc: "03" },
  { country: "Paraguay", operator: "Tigo", mcc: "744", mnc: "02" },
  { country: "Paraguay", operator: "Personal", mcc: "744", mnc: "05" },
  { country: "Uruguay", operator: "Antel", mcc: "748", mnc: "01" },
  { country: "Uruguay", operator: "Movistar", mcc: "748", mnc: "07" },

  // ====== Western Europe ======
  { country: "United Kingdom", operator: "EE", mcc: "234", mnc: "30" },
  { country: "United Kingdom", operator: "O2", mcc: "234", mnc: "10" },
  { country: "United Kingdom", operator: "Vodafone UK", mcc: "234", mnc: "15" },
  { country: "United Kingdom", operator: "Three", mcc: "234", mnc: "20" },
  { country: "Germany", operator: "Deutsche Telekom", mcc: "262", mnc: "01" },
  { country: "Germany", operator: "Vodafone DE", mcc: "262", mnc: "02" },
  { country: "Germany", operator: "O2 DE", mcc: "262", mnc: "03" },
  { country: "Germany", operator: "1&1 Drillisch", mcc: "262", mnc: "23" },
  { country: "France", operator: "Orange", mcc: "208", mnc: "01" },
  { country: "France", operator: "SFR", mcc: "208", mnc: "10" },
  { country: "France", operator: "Bouygues", mcc: "208", mnc: "20" },
  { country: "France", operator: "Free Mobile", mcc: "208", mnc: "15" },
  { country: "Italy", operator: "TIM", mcc: "222", mnc: "01" },
  { country: "Italy", operator: "Vodafone IT", mcc: "222", mnc: "10" },
  { country: "Italy", operator: "WindTre", mcc: "222", mnc: "88" },
  { country: "Italy", operator: "Iliad IT", mcc: "222", mnc: "50" },
  { country: "Spain", operator: "Movistar", mcc: "214", mnc: "07" },
  { country: "Spain", operator: "Vodafone ES", mcc: "214", mnc: "01" },
  { country: "Spain", operator: "Orange ES", mcc: "214", mnc: "03" },
  { country: "Spain", operator: "Yoigo", mcc: "214", mnc: "04" },
  { country: "Netherlands", operator: "KPN", mcc: "204", mnc: "08" },
  { country: "Netherlands", operator: "Vodafone NL", mcc: "204", mnc: "04" },
  { country: "Netherlands", operator: "T-Mobile NL", mcc: "204", mnc: "16" },
  { country: "Belgium", operator: "Proximus", mcc: "206", mnc: "01" },
  { country: "Belgium", operator: "Orange BE", mcc: "206", mnc: "10" },
  { country: "Belgium", operator: "Telenet/Base", mcc: "206", mnc: "20" },
  { country: "Switzerland", operator: "Swisscom", mcc: "228", mnc: "01" },
  { country: "Switzerland", operator: "Sunrise", mcc: "228", mnc: "02" },
  { country: "Switzerland", operator: "Salt", mcc: "228", mnc: "03" },
  { country: "Austria", operator: "A1 Telekom", mcc: "232", mnc: "01" },
  { country: "Austria", operator: "Magenta (T-Mobile)", mcc: "232", mnc: "03" },
  { country: "Austria", operator: "Drei (3)", mcc: "232", mnc: "10" },
  { country: "Sweden", operator: "Telia", mcc: "240", mnc: "01" },
  { country: "Sweden", operator: "Tele2", mcc: "240", mnc: "07" },
  { country: "Sweden", operator: "Telenor SE", mcc: "240", mnc: "08" },
  { country: "Norway", operator: "Telenor", mcc: "242", mnc: "01" },
  { country: "Norway", operator: "Telia NO", mcc: "242", mnc: "02" },
  { country: "Denmark", operator: "TDC", mcc: "238", mnc: "01" },
  { country: "Denmark", operator: "Telenor DK", mcc: "238", mnc: "02" },
  { country: "Finland", operator: "Elisa", mcc: "244", mnc: "05" },
  { country: "Finland", operator: "Telia", mcc: "244", mnc: "03" },
  { country: "Finland", operator: "DNA", mcc: "244", mnc: "12" },
  { country: "Ireland", operator: "Vodafone IE", mcc: "272", mnc: "01" },
  { country: "Ireland", operator: "Three IE", mcc: "272", mnc: "05" },
  { country: "Ireland", operator: "Eir", mcc: "272", mnc: "03" },
  { country: "Portugal", operator: "NOS", mcc: "268", mnc: "03" },
  { country: "Portugal", operator: "MEO", mcc: "268", mnc: "06" },
  { country: "Portugal", operator: "Vodafone PT", mcc: "268", mnc: "01" },
  { country: "Greece", operator: "Cosmote", mcc: "202", mnc: "01" },
  { country: "Greece", operator: "Vodafone GR", mcc: "202", mnc: "05" },
  { country: "Greece", operator: "Nova", mcc: "202", mnc: "14" },

  // ====== Eastern Europe ======
  { country: "Poland", operator: "Orange PL", mcc: "260", mnc: "03" },
  { country: "Poland", operator: "T-Mobile PL", mcc: "260", mnc: "02" },
  { country: "Poland", operator: "Play", mcc: "260", mnc: "06" },
  { country: "Poland", operator: "Plus", mcc: "260", mnc: "01" },
  { country: "Romania", operator: "Orange RO", mcc: "226", mnc: "10" },
  { country: "Romania", operator: "Vodafone RO", mcc: "226", mnc: "01" },
  { country: "Romania", operator: "Digi", mcc: "226", mnc: "05" },
  { country: "Czech Republic", operator: "T-Mobile CZ", mcc: "230", mnc: "01" },
  { country: "Czech Republic", operator: "O2 CZ", mcc: "230", mnc: "02" },
  { country: "Czech Republic", operator: "Vodafone CZ", mcc: "230", mnc: "03" },
  { country: "Hungary", operator: "Telekom HU", mcc: "216", mnc: "30" },
  { country: "Hungary", operator: "Yettel", mcc: "216", mnc: "01" },
  { country: "Hungary", operator: "Vodafone HU", mcc: "216", mnc: "70" },
  { country: "Ukraine", operator: "Kyivstar", mcc: "255", mnc: "03" },
  { country: "Ukraine", operator: "Vodafone UA", mcc: "255", mnc: "01" },
  { country: "Ukraine", operator: "Lifecell", mcc: "255", mnc: "06" },
  { country: "Bulgaria", operator: "A1 BG", mcc: "284", mnc: "01" },
  { country: "Bulgaria", operator: "Yettel BG", mcc: "284", mnc: "05" },
  { country: "Bulgaria", operator: "Vivacom", mcc: "284", mnc: "03" },
  { country: "Serbia", operator: "A1 SRB", mcc: "220", mnc: "05" },
  { country: "Serbia", operator: "Yettel SRB", mcc: "220", mnc: "01" },
  { country: "Serbia", operator: "MTS", mcc: "220", mnc: "03" },
  { country: "Croatia", operator: "HT", mcc: "219", mnc: "01" },
  { country: "Croatia", operator: "A1 HR", mcc: "219", mnc: "10" },
  { country: "Croatia", operator: "Telemach", mcc: "219", mnc: "02" },
  { country: "Slovakia", operator: "Orange SK", mcc: "231", mnc: "01" },
  { country: "Slovakia", operator: "Telekom SK", mcc: "231", mnc: "02" },
  { country: "Slovenia", operator: "A1 SI", mcc: "293", mnc: "40" },
  { country: "Slovenia", operator: "Telekom SI", mcc: "293", mnc: "70" },
  { country: "Lithuania", operator: "Telia", mcc: "246", mnc: "01" },
  { country: "Lithuania", operator: "Tele2", mcc: "246", mnc: "03" },
  { country: "Latvia", operator: "LMT", mcc: "247", mnc: "01" },
  { country: "Latvia", operator: "Tele2", mcc: "247", mnc: "02" },
  { country: "Latvia", operator: "Bite", mcc: "247", mnc: "05" },
  { country: "Estonia", operator: "Telia", mcc: "248", mnc: "01" },
  { country: "Estonia", operator: "Tele2", mcc: "248", mnc: "03" },
  { country: "Estonia", operator: "Elisa", mcc: "248", mnc: "02" },
  { country: "Russia", operator: "MTS", mcc: "250", mnc: "01" },
  { country: "Russia", operator: "MegaFon", mcc: "250", mnc: "02" },
  { country: "Russia", operator: "Beeline", mcc: "250", mnc: "99" },
  { country: "Russia", operator: "Tele2 RU", mcc: "250", mnc: "20" },
  { country: "Turkey", operator: "Turkcell", mcc: "286", mnc: "01" },
  { country: "Turkey", operator: "Vodafone TR", mcc: "286", mnc: "02" },
  { country: "Turkey", operator: "Turk Telekom", mcc: "286", mnc: "03" },

  // ====== Middle East & Gulf ======
  { country: "UAE", operator: "Etisalat", mcc: "424", mnc: "02" },
  { country: "UAE", operator: "du", mcc: "424", mnc: "03" },
  { country: "Saudi Arabia", operator: "STC", mcc: "420", mnc: "01" },
  { country: "Saudi Arabia", operator: "Mobily", mcc: "420", mnc: "03" },
  { country: "Saudi Arabia", operator: "Zain KSA", mcc: "420", mnc: "04" },
  { country: "Qatar", operator: "Ooredoo", mcc: "427", mnc: "01" },
  { country: "Qatar", operator: "Vodafone QA", mcc: "427", mnc: "02" },
  { country: "Kuwait", operator: "Zain", mcc: "419", mnc: "02" },
  { country: "Kuwait", operator: "Ooredoo KW", mcc: "419", mnc: "03" },
  { country: "Kuwait", operator: "STC KW", mcc: "419", mnc: "04" },
  { country: "Bahrain", operator: "Batelco", mcc: "426", mnc: "01" },
  { country: "Bahrain", operator: "Zain BH", mcc: "426", mnc: "02" },
  { country: "Bahrain", operator: "STC BH", mcc: "426", mnc: "04" },
  { country: "Oman", operator: "Omantel", mcc: "422", mnc: "02" },
  { country: "Oman", operator: "Ooredoo OM", mcc: "422", mnc: "03" },
  { country: "Oman", operator: "Vodafone OM", mcc: "422", mnc: "04" },
  { country: "Jordan", operator: "Zain JO", mcc: "416", mnc: "01" },
  { country: "Jordan", operator: "Orange JO", mcc: "416", mnc: "77" },
  { country: "Jordan", operator: "Umniah", mcc: "416", mnc: "03" },
  { country: "Lebanon", operator: "Alfa", mcc: "415", mnc: "01" },
  { country: "Lebanon", operator: "Touch", mcc: "415", mnc: "03" },
  { country: "Iraq", operator: "Zain IQ", mcc: "418", mnc: "20" },
  { country: "Iraq", operator: "Asiacell", mcc: "418", mnc: "05" },
  { country: "Iraq", operator: "Korek", mcc: "418", mnc: "40" },
  { country: "Iran", operator: "Hamrah-e Aval", mcc: "432", mnc: "11" },
  { country: "Iran", operator: "Irancell", mcc: "432", mnc: "35" },
  { country: "Iran", operator: "Rightel", mcc: "432", mnc: "20" },
  { country: "Israel", operator: "Cellcom", mcc: "425", mnc: "02" },
  { country: "Israel", operator: "Partner", mcc: "425", mnc: "01" },
  { country: "Israel", operator: "Pelephone", mcc: "425", mnc: "03" },
  { country: "Egypt", operator: "Vodafone EG", mcc: "602", mnc: "02" },
  { country: "Egypt", operator: "Orange EG", mcc: "602", mnc: "01" },
  { country: "Egypt", operator: "Etisalat Masr", mcc: "602", mnc: "03" },
  { country: "Egypt", operator: "WE", mcc: "602", mnc: "04" },

  // ====== South Asia ======
  { country: "India", operator: "Airtel", mcc: "404", mnc: "02" },
  { country: "India", operator: "Vodafone Idea (Vi)", mcc: "404", mnc: "22" },
  { country: "India", operator: "Reliance Jio", mcc: "405", mnc: "840" },
  { country: "India", operator: "BSNL", mcc: "404", mnc: "53" },
  { country: "Pakistan", operator: "Jazz", mcc: "410", mnc: "01" },
  { country: "Pakistan", operator: "Telenor PK", mcc: "410", mnc: "06" },
  { country: "Pakistan", operator: "Zong", mcc: "410", mnc: "04" },
  { country: "Pakistan", operator: "Ufone", mcc: "410", mnc: "03" },
  { country: "Bangladesh", operator: "Grameenphone", mcc: "470", mnc: "01" },
  { country: "Bangladesh", operator: "Banglalink", mcc: "470", mnc: "03" },
  { country: "Bangladesh", operator: "Robi", mcc: "470", mnc: "02" },
  { country: "Bangladesh", operator: "Teletalk", mcc: "470", mnc: "04" },
  { country: "Sri Lanka", operator: "Dialog", mcc: "413", mnc: "02" },
  { country: "Sri Lanka", operator: "Mobitel", mcc: "413", mnc: "01" },
  { country: "Sri Lanka", operator: "Hutch", mcc: "413", mnc: "08" },
  { country: "Nepal", operator: "Ncell", mcc: "429", mnc: "01" },
  { country: "Nepal", operator: "Nepal Telecom", mcc: "429", mnc: "02" },
  { country: "Afghanistan", operator: "AWCC", mcc: "412", mnc: "01" },
  { country: "Afghanistan", operator: "Roshan", mcc: "412", mnc: "20" },
  { country: "Afghanistan", operator: "MTN AF", mcc: "412", mnc: "40" },
  { country: "Afghanistan", operator: "Etisalat AF", mcc: "412", mnc: "50" },

  // ====== Southeast Asia ======
  { country: "Philippines", operator: "Globe", mcc: "515", mnc: "02" },
  { country: "Philippines", operator: "Smart", mcc: "515", mnc: "03" },
  { country: "Philippines", operator: "DITO", mcc: "515", mnc: "66" },
  { country: "Indonesia", operator: "Telkomsel", mcc: "510", mnc: "10" },
  { country: "Indonesia", operator: "XL Axiata", mcc: "510", mnc: "11" },
  { country: "Indonesia", operator: "Indosat", mcc: "510", mnc: "01" },
  { country: "Indonesia", operator: "Smartfren", mcc: "510", mnc: "28" },
  { country: "Malaysia", operator: "Maxis", mcc: "502", mnc: "12" },
  { country: "Malaysia", operator: "CelcomDigi", mcc: "502", mnc: "19" },
  { country: "Malaysia", operator: "U Mobile", mcc: "502", mnc: "18" },
  { country: "Malaysia", operator: "Unifi Mobile", mcc: "502", mnc: "153" },
  { country: "Thailand", operator: "AIS", mcc: "520", mnc: "01" },
  { country: "Thailand", operator: "TrueMove", mcc: "520", mnc: "00" },
  { country: "Thailand", operator: "DTAC", mcc: "520", mnc: "18" },
  { country: "Vietnam", operator: "Viettel", mcc: "452", mnc: "04" },
  { country: "Vietnam", operator: "Vinaphone", mcc: "452", mnc: "02" },
  { country: "Vietnam", operator: "Mobifone", mcc: "452", mnc: "01" },
  { country: "Singapore", operator: "Singtel", mcc: "525", mnc: "01" },
  { country: "Singapore", operator: "StarHub", mcc: "525", mnc: "05" },
  { country: "Singapore", operator: "M1", mcc: "525", mnc: "03" },
  { country: "Singapore", operator: "SIMBA", mcc: "525", mnc: "10" },
  { country: "Myanmar", operator: "MPT", mcc: "414", mnc: "01" },
  { country: "Myanmar", operator: "Ooredoo MM", mcc: "414", mnc: "05" },
  { country: "Myanmar", operator: "Telenor MM", mcc: "414", mnc: "06" },
  { country: "Cambodia", operator: "Metfone", mcc: "456", mnc: "08" },
  { country: "Cambodia", operator: "Smart Axiata", mcc: "456", mnc: "06" },
  { country: "Cambodia", operator: "Cellcard", mcc: "456", mnc: "01" },
  { country: "Laos", operator: "Unitel", mcc: "457", mnc: "03" },
  { country: "Laos", operator: "Lao Telecom", mcc: "457", mnc: "01" },
  { country: "Brunei", operator: "DST", mcc: "528", mnc: "11" },
  { country: "Brunei", operator: "Progresif", mcc: "528", mnc: "02" },
  { country: "East Timor", operator: "Timor Telecom", mcc: "514", mnc: "01" },
  { country: "East Timor", operator: "Telkomcel", mcc: "514", mnc: "02" },

  // ====== East Asia ======
  { country: "China", operator: "China Mobile", mcc: "460", mnc: "00" },
  { country: "China", operator: "China Unicom", mcc: "460", mnc: "01" },
  { country: "China", operator: "China Telecom", mcc: "460", mnc: "03" },
  { country: "Hong Kong", operator: "CMHK", mcc: "454", mnc: "12" },
  { country: "Hong Kong", operator: "CSL", mcc: "454", mnc: "00" },
  { country: "Hong Kong", operator: "3 HK", mcc: "454", mnc: "03" },
  { country: "Hong Kong", operator: "SmarTone", mcc: "454", mnc: "06" },
  { country: "Taiwan", operator: "Chunghwa Telecom", mcc: "466", mnc: "92" },
  { country: "Taiwan", operator: "Taiwan Mobile", mcc: "466", mnc: "97" },
  { country: "Taiwan", operator: "FarEasTone", mcc: "466", mnc: "01" },
  { country: "South Korea", operator: "SK Telecom", mcc: "450", mnc: "05" },
  { country: "South Korea", operator: "KT", mcc: "450", mnc: "08" },
  { country: "South Korea", operator: "LG U+", mcc: "450", mnc: "06" },
  { country: "Japan", operator: "NTT Docomo", mcc: "440", mnc: "10" },
  { country: "Japan", operator: "SoftBank", mcc: "440", mnc: "20" },
  { country: "Japan", operator: "KDDI (au)", mcc: "440", mnc: "50" },
  { country: "Japan", operator: "Rakuten Mobile", mcc: "440", mnc: "11" },
  { country: "Macau", operator: "CTM", mcc: "455", mnc: "01" },
  { country: "Macau", operator: "3 MO", mcc: "455", mnc: "03" },
  { country: "Macau", operator: "SmarTone MO", mcc: "455", mnc: "00" },
  { country: "Mongolia", operator: "Mobicom", mcc: "428", mnc: "99" },
  { country: "Mongolia", operator: "Unitel", mcc: "428", mnc: "88" },

  // ====== Oceania ======
  { country: "Australia", operator: "Telstra", mcc: "505", mnc: "01" },
  { country: "Australia", operator: "Optus", mcc: "505", mnc: "02" },
  { country: "Australia", operator: "Vodafone AU", mcc: "505", mnc: "03" },
  { country: "New Zealand", operator: "Spark", mcc: "530", mnc: "01" },
  { country: "New Zealand", operator: "One NZ", mcc: "530", mnc: "05" },
  { country: "New Zealand", operator: "2degrees", mcc: "530", mnc: "24" },
  { country: "Fiji", operator: "Digicel", mcc: "542", mnc: "02" },
  { country: "Fiji", operator: "Vodafone FJ", mcc: "542", mnc: "01" },
  { country: "Papua New Guinea", operator: "Digicel", mcc: "537", mnc: "03" },
  { country: "Papua New Guinea", operator: "bemobile", mcc: "537", mnc: "01" },

  // ====== Africa ======
  { country: "Nigeria", operator: "MTN NG", mcc: "621", mnc: "30" },
  { country: "Nigeria", operator: "Airtel NG", mcc: "621", mnc: "20" },
  { country: "Nigeria", operator: "Globacom", mcc: "621", mnc: "50" },
  { country: "Nigeria", operator: "9mobile", mcc: "621", mnc: "60" },
  { country: "South Africa", operator: "Vodacom", mcc: "655", mnc: "01" },
  { country: "South Africa", operator: "MTN SA", mcc: "655", mnc: "10" },
  { country: "South Africa", operator: "Cell C", mcc: "655", mnc: "07" },
  { country: "South Africa", operator: "Telkom Mobile", mcc: "655", mnc: "02" },
  { country: "Kenya", operator: "Safaricom", mcc: "639", mnc: "02" },
  { country: "Kenya", operator: "Airtel KE", mcc: "639", mnc: "03" },
  { country: "Kenya", operator: "Telkom KE", mcc: "639", mnc: "07" },
  { country: "Ethiopia", operator: "Ethio Telecom", mcc: "636", mnc: "01" },
  { country: "Ethiopia", operator: "Safaricom ET", mcc: "636", mnc: "02" },
  { country: "Ghana", operator: "MTN GH", mcc: "620", mnc: "01" },
  { country: "Ghana", operator: "Vodafone GH", mcc: "620", mnc: "02" },
  { country: "Ghana", operator: "AirtelTigo", mcc: "620", mnc: "06" },
  { country: "Tanzania", operator: "Vodacom TZ", mcc: "640", mnc: "02" },
  { country: "Tanzania", operator: "Airtel TZ", mcc: "640", mnc: "05" },
  { country: "Tanzania", operator: "Tigo TZ", mcc: "640", mnc: "03" },
  { country: "Uganda", operator: "MTN UG", mcc: "641", mnc: "10" },
  { country: "Uganda", operator: "Airtel UG", mcc: "641", mnc: "01" },
  { country: "Ivory Coast", operator: "Orange CI", mcc: "612", mnc: "03" },
  { country: "Ivory Coast", operator: "MTN CI", mcc: "612", mnc: "05" },
  { country: "Ivory Coast", operator: "Moov", mcc: "612", mnc: "02" },
  { country: "Cameroon", operator: "Orange CM", mcc: "624", mnc: "02" },
  { country: "Cameroon", operator: "MTN CM", mcc: "624", mnc: "01" },
  { country: "Senegal", operator: "Orange SN", mcc: "608", mnc: "01" },
  { country: "Senegal", operator: "Free SN", mcc: "608", mnc: "02" },
  { country: "DR Congo", operator: "Vodacom", mcc: "630", mnc: "01" },
  { country: "DR Congo", operator: "Airtel CD", mcc: "630", mnc: "02" },
  { country: "DR Congo", operator: "Orange CD", mcc: "630", mnc: "86" },
  { country: "Angola", operator: "Unitel", mcc: "631", mnc: "02" },
  { country: "Angola", operator: "Movicel", mcc: "631", mnc: "04" },
  { country: "Morocco", operator: "Maroc Telecom", mcc: "604", mnc: "01" },
  { country: "Morocco", operator: "Orange MA", mcc: "604", mnc: "00" },
  { country: "Morocco", operator: "Inwi", mcc: "604", mnc: "02" },
  { country: "Algeria", operator: "Mobilis", mcc: "603", mnc: "01" },
  { country: "Algeria", operator: "Djezzy", mcc: "603", mnc: "02" },
  { country: "Algeria", operator: "Ooredoo DZ", mcc: "603", mnc: "03" },
  { country: "Tunisia", operator: "Tunisie Telecom", mcc: "605", mnc: "01" },
  { country: "Tunisia", operator: "Orange TN", mcc: "605", mnc: "02" },
  { country: "Tunisia", operator: "Ooredoo TN", mcc: "605", mnc: "03" },
  { country: "Libya", operator: "Al-Madar", mcc: "606", mnc: "01" },
  { country: "Libya", operator: "Libyana", mcc: "606", mnc: "00" },
  { country: "Sudan", operator: "Zain SD", mcc: "634", mnc: "01" },
  { country: "Sudan", operator: "MTN SD", mcc: "634", mnc: "02" },
  { country: "Sudan", operator: "Sudani", mcc: "634", mnc: "07" },
  { country: "Rwanda", operator: "MTN RW", mcc: "635", mnc: "10" },
  { country: "Rwanda", operator: "Airtel RW", mcc: "635", mnc: "13" },
  { country: "Zambia", operator: "MTN ZM", mcc: "645", mnc: "01" },
  { country: "Zambia", operator: "Airtel ZM", mcc: "645", mnc: "02" },
  { country: "Zimbabwe", operator: "Econet", mcc: "648", mnc: "04" },
  { country: "Zimbabwe", operator: "NetOne", mcc: "648", mnc: "01" },
  { country: "Mozambique", operator: "Mcel", mcc: "643", mnc: "01" },
  { country: "Mozambique", operator: "Vodacom MZ", mcc: "643", mnc: "04" },
  { country: "Malawi", operator: "Airtel MW", mcc: "650", mnc: "10" },
  { country: "Malawi", operator: "TNM", mcc: "650", mnc: "01" },
  { country: "Mauritius", operator: "Orange MU", mcc: "617", mnc: "01" },
  { country: "Mauritius", operator: "Emtel", mcc: "617", mnc: "10" },
  { country: "Botswana", operator: "Mascom", mcc: "652", mnc: "01" },
  { country: "Botswana", operator: "Orange BW", mcc: "652", mnc: "02" },
  { country: "Namibia", operator: "MTC", mcc: "649", mnc: "01" },
  { country: "Namibia", operator: "TN Mobile", mcc: "649", mnc: "02" },
  { country: "Gabon", operator: "Airtel GA", mcc: "628", mnc: "02" },
  { country: "Gabon", operator: "Moov", mcc: "628", mnc: "04" },
  { country: "Benin", operator: "MTN BJ", mcc: "616", mnc: "01" },
  { country: "Benin", operator: "Moov", mcc: "616", mnc: "02" },
  { country: "Burkina Faso", operator: "Orange BF", mcc: "613", mnc: "01" },
  { country: "Burkina Faso", operator: "Moov", mcc: "613", mnc: "03" },
  { country: "Mali", operator: "Orange ML", mcc: "610", mnc: "02" },
  { country: "Mali", operator: "Moov", mcc: "610", mnc: "01" },
  { country: "Niger", operator: "Airtel NE", mcc: "614", mnc: "01" },
  { country: "Niger", operator: "Orange NE", mcc: "614", mnc: "04" },
  { country: "Guinea", operator: "Orange GN", mcc: "611", mnc: "02" },
  { country: "Guinea", operator: "MTN GN", mcc: "611", mnc: "04" },
  { country: "Sierra Leone", operator: "Orange SL", mcc: "619", mnc: "01" },
  { country: "Sierra Leone", operator: "Africell", mcc: "619", mnc: "25" },
  { country: "Liberia", operator: "Orange LR", mcc: "618", mnc: "04" },
  { country: "Liberia", operator: "MTN LR", mcc: "618", mnc: "01" },

  // ====== Central Asia & Caucasus ======
  { country: "Kazakhstan", operator: "Kcell", mcc: "401", mnc: "02" },
  { country: "Kazakhstan", operator: "Beeline KZ", mcc: "401", mnc: "01" },
  { country: "Kazakhstan", operator: "Tele2 KZ", mcc: "401", mnc: "77" },
  { country: "Uzbekistan", operator: "Ucell", mcc: "434", mnc: "05" },
  { country: "Uzbekistan", operator: "Beeline UZ", mcc: "434", mnc: "04" },
  { country: "Uzbekistan", operator: "UMS", mcc: "434", mnc: "01" },
  { country: "Azerbaijan", operator: "Azercell", mcc: "400", mnc: "01" },
  { country: "Azerbaijan", operator: "Bakcell", mcc: "400", mnc: "02" },
  { country: "Azerbaijan", operator: "Nar", mcc: "400", mnc: "04" },
  { country: "Georgia", operator: "MagtiCom", mcc: "282", mnc: "01" },
  { country: "Georgia", operator: "Beeline GE", mcc: "282", mnc: "04" },
  { country: "Georgia", operator: "Silknet", mcc: "282", mnc: "05" },
  { country: "Armenia", operator: "Viva-MTS", mcc: "283", mnc: "05" },
  { country: "Armenia", operator: "Ucom", mcc: "283", mnc: "10" },
  { country: "Armenia", operator: "Team", mcc: "283", mnc: "01" },
  { country: "Tajikistan", operator: "Tcell", mcc: "436", mnc: "01" },
  { country: "Tajikistan", operator: "MegaFon TJ", mcc: "436", mnc: "05" },
  { country: "Kyrgyzstan", operator: "MegaCom", mcc: "437", mnc: "05" },
  { country: "Kyrgyzstan", operator: "Beeline KG", mcc: "437", mnc: "01" },
  { country: "Turkmenistan", operator: "TM Cell", mcc: "438", mnc: "01" },

  // ====== Caribbean ======
  { country: "Jamaica", operator: "Digicel", mcc: "338", mnc: "050" },
  { country: "Jamaica", operator: "Flow", mcc: "338", mnc: "020" },
  { country: "Trinidad & Tobago", operator: "Digicel", mcc: "374", mnc: "130" },
  { country: "Trinidad & Tobago", operator: "bmobile", mcc: "374", mnc: "12" },
  { country: "Haiti", operator: "Digicel", mcc: "372", mnc: "01" },
  { country: "Haiti", operator: "Natcom", mcc: "372", mnc: "02" },
  { country: "Bahamas", operator: "BTC", mcc: "364", mnc: "390" },
  { country: "Barbados", operator: "Digicel", mcc: "342", mnc: "600" },
  { country: "Barbados", operator: "Flow", mcc: "342", mnc: "750" },
  { country: "Guyana", operator: "Digicel", mcc: "738", mnc: "01" },
  { country: "Guyana", operator: "GTT", mcc: "738", mnc: "02" },
  { country: "Suriname", operator: "Telesur", mcc: "746", mnc: "02" },
  { country: "Suriname", operator: "Digicel", mcc: "746", mnc: "03" },
  { country: "Cuba", operator: "Cubacel", mcc: "368", mnc: "01" },
];

export async function POST() {
  const user = await verifySession();
  if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

  try {
    // Create table if not exists
    await executeVos(`
      CREATE TABLE IF NOT EXISTS e_mccmnc (
        id INT AUTO_INCREMENT PRIMARY KEY,
        country VARCHAR(100) NOT NULL,
        operator VARCHAR(150) NOT NULL DEFAULT '',
        mcc VARCHAR(10) NOT NULL DEFAULT '',
        mnc VARCHAR(10) NOT NULL DEFAULT '',
        INDEX idx_country (country),
        INDEX idx_mcc (mcc)
      )
    `);

    // Seed
    let inserted = 0;
    for (const entry of SEED_DATA) {
      try {
        await executeVos(
          "INSERT INTO e_mccmnc (country, operator, mcc, mnc) VALUES (?,?,?,?)",
          [entry.country, entry.operator, entry.mcc, entry.mnc]
        );
        inserted++;
      } catch { /* duplicates */ }
    }

    return NextResponse.json({ success: true, inserted, total: SEED_DATA.length });
  } catch (error) {
    return NextResponse.json({ error: error instanceof Error ? error.message : "Seed failed" }, { status: 500 });
  }
}
