[Trace]
TRACE_TO_FILE=true
TRACE_FILE_LENGTH=4096
TRACE_MASK=ERROR
TRACE_MAX_FILE=10
TRACE_TO_SCREEN=false

[MgcApi]
NAME=WebServer_51.161.47.101
MANAGEMENT_SERVER_IP=127.0.0.1
MANAGEMENT_SERVER_PORT=1203
WEBDATA_SERVER_IP=127.0.0.1
WEBDATA_SERVER_PORT=1210
CC3000_SERVER_IP=
CC3000_SERVER_PORT=1232
